accept = [200, 201, 204, 206, 301, 302, 429]
timeout = 20
max_retries = 3
exclude_all_private = true
exclude = [
  "^https?://localhost",
  "^https?://127\\.",
  "^mailto:",
  "stackexchange.com",
  "visitor-badge.laobi.icu",
]
